name: Continuous Integration

on:
  push:
    branches:
    - github-build

  pull_request:
    branches:
    - github-build

  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        cc: [msvc, gcc, clang]
        exclude:
          - os: ubuntu-latest
            cc: msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: setup mingw
        if: ${{ matrix.os == 'windows-latest' && matrix.cc == 'gcc' }}
        uses: egor-tensin/setup-gcc@v1

      - name: setup gcc
        if: ${{ matrix.cc == 'gcc' }}
        uses: egor-tensin/setup-gcc@v1

      - name: setup clang
        if: ${{ matrix.cc == 'clang' }}
        uses: egor-tensin/setup-clang@v1

      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: configure
        run: cmake . -B build -G Ninja

      - name: build
        run: cmake --build build

      - name: test
        run: ctest --test-dir build
