name: Continuous Integration

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cc: [cl, gcc, clang]
        exclude:
          - os: ubuntu-latest
            cc: cl
          - os: windows-latest
            cc: gcc
          - os: windows-latest
            cc: clang

    runs-on: ${{ matrix.os }}

    steps:

      - name: setup gcc
        if: matrix.cc == 'gcc'
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 13

      - name: setup clang
        if: matrix.cc == 'clang'
        uses: egor-tensin/setup-clang@v1
        with:
          version: 16

      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: configure
        run: cmake . -B build

      - name: build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: test
        run: ctest --test-dir build
