name: Continuous Integration

on:
  push:
    branches:
    - github-build

  pull_request:
    branches:
    - github-build

  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cc: [cl, gcc, clang]
        exclude:
          - os: ubuntu-latest
            cc: cl
          - os: windows-latest
            cc: gcc

    runs-on: ${{ matrix.os }}

    steps:
      - name: setup mingw
        if: matrix.os == 'windows-latest' && matrix.cc == 'gcc'
        uses: egor-tensin/setup-mingw@v2

      - name: setup gcc
        if: matrix.cc == 'gcc'
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 13

      - name: setup clang
        if: matrix.cc == 'clang'
        uses: egor-tensin/setup-clang@v1
        with:
          version: 16

      - name: setup msvc
        if: matrix.cc == 'cl'
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64

      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: configure
        run: cmake . -B build -DCMAKE_C_COMPILER=${{matrix.cc}} -DCMAKE_CXX_COMPILER=${{matrix.cc}}

      - name: build
        run: cmake --build build

      - name: test
        run: ctest --test-dir build
